#!/bin/sh

PLAYHOME=/home/andersh/javaapp/play-1.2.4/
BISCONFHOME=/home/andersh/development/bisconf
BISHOME=/home/andersh/development/bischeck

CLASSBIS=$BISHOME/target/classes:$BISHOME/target/resources:$BISHOME/lib/quartz-2.0.1.jar

CLASSCONF=$BISCONFHOME/lib/*:$BISCONFHOME/conf

CLASSPLAY=$PLAYHOME/framework/play-1.2.4.jar:$PLAYHOME/framework/lib/*

CLASSPATH=$CLASSCONF:$CLASSBIS:$CLASSPLAY


java -classpath $CLASSPATH  -Dbisconfhome=$BISCONFHOME -Dbishome=/opt/socbox/addons/bischeck -Dplay.id= -Dapplication.path=$BISCONFHOME -Djava.endorsed.dirs=$PLAYHOME/framework/endorsed  -Dfile.encoding=UTF-8  play.server.Server